spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_sys?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: txy813
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hunau.domain  # 注意：对应实体类的路